mesonbuild/meson-python

mesonpy.py, noxfile.py, tests/packages/configure-data/configure_data.py.in, tests/packages/configure-data/meson.build, tests/packages/configure-data/pyproject.toml, tests/test_wheel.py
This will map files that do not use {py_purelib}/{py_platlib}
placeholders, which is the case of targets that receive the install
location as a string in the Meson build files (eg. configure_file).
=> mesonpy: add heuristics to try mapping unknown install paths to wheel

tests/test_wheel.py
This has been very flaky, as it depends on how external dependencies,
like auditwheel, handle things, so let's just filter directory entries
out from the wheel content tests.
=> tests: fix wheel content tests

mesonpy/__init__.py, tests/packages/dynamic-version/meson.build, tests/packages/dynamic-version/pyproject.toml, tests/test_metadata.py
I think this broke with pep621 changes.
=> mesonpy: fix getting the version from Meson

mesonpy/__init__.py, tests/test_pep517.py
=> mesonpy: the patchelf dependency is Posix only

.github/workflows/tests-cygwin.yml, mesonpy/__init__.py, tests/test_pep517.py, tests/test_wheel.py
On Cygwin os.name returns "posix", so we need to check for "Linux" in
platform.system() instead.
=> mesonpy: fix Cygwin compability

mesonpy/__init__.py, tests/test_pep517.py
Also move to the patchelf package instead of patchelf-wrapper as the
it's functionality is no longer needed and patchelf is better
maintained.
Fixed #52
=> mesonpy: only pull patchelf if needed

mesonpy/__init__.py, mesonpy/_util.py, pyproject.toml, tests/packages/subdirs/meson.build, tests/packages/subdirs/pyproject.toml, tests/test_sdist.py
=> mesonpy: include uncommited changes in sdist

mesonpy/__init__.py, tests/test_pep517.py
`ninja` is a dependency in `pyproject.toml` already, so it can be removed in `__init__.py`.
Follows up on https://github.com/FFY00/meson-python/pull/63#issuecomment-1136311433
=> Clean up duplicate dependency on ninja

mesonpy/__init__.py, pyproject.toml
=> mesonpy: replace pep621 dependency with pyproject-metadata

mesonpy/__init__.py
=> mesonpy: skip unsure platlib warning on Debian if the file is in moduledir

.gitignore, mesonpy/__init__.py
The version reported by the 3.10 CPython branch is "3.10.5+" which fails the
metadata check.
This strips any trailing '+'.
=> Support the maintenance branches of CPython

mesonpy/__init__.py
See https://github.com/scipy/scipy/issues/16446 for details on how it fails on macOS and also for proof that it is not needed because it does not change the wheel size on Linux.
This was originally discussed in gh-27. It looks like I was wrong there about the need for stripping. That info was based on my experience with `numpy.distutils` builds; there it is needed because of the hardcoded debug flags that cannot be switched with a flag like `-Ddebug=false` like we use in `meson-python`.
=> BUG: remove `-Dstrip=true` default, it doesn't work on macOS

tests/test_metadata.py
=> TST: fix tests for pyproject-metadata 0.6.1

docs/index.rst
For the `.gitattributes` content, I tested that this works as advertised in SciPy. The info came from gh-58.
=> DOC: extend documentation on what's included/excluded in sdist and wheels

tests/test_wheel.py
=> TST: mark test_local_lib as xfail on github actions

mesonpy/__init__.py
=> BUG: add minor version to MacOS 11 and 12 tags as workaround

pyproject.toml
This dependency was bumped from 0.60.0 to 0.62.0 in gh-58, but only in one of the two places where it was needed. These two places should probably always be kept consistent with each other, even though technically it's not _required_.
=> MAINT: ensure minimum Meson version is consistent in pyproject.toml

mesonpy/__init__.py, tests/packages/executable-bit/example-script.py, tests/packages/executable-bit/example.c, tests/packages/executable-bit/executable_module.py, tests/packages/executable-bit/meson.build, tests/packages/executable-bit/pyproject.toml, tests/test_sdist.py, tests/test_wheel.py
Closes gh-82
Note that the bug report is only about the sdist. The wheel generation uses `shutil.copy2`, which should do the right thing already.
=> BUG: preserve file permissions for sdist

pyproject.toml
I just tried to click these links and noticed that they didn't work.
=> DOC: correct RTD links for PyPI

mesonpy/__init__.py, pyproject.toml
This seems to have been fixed, so we can now start to use them.
See https://github.com/FFY00/meson-python/issues/95#issuecomment-1179215646
=> ENH: use Meson paths based on {moduledir_shared}

mesonpy/__init__.py
This attempted to override "python3", which Meson never used for find_installation. So the native file did nothing.
Override the correct name.
=> BUG: fix native file override

.github/workflows/ci-sage.yml
They were firing in duplicate when a push was made to a branch and a PR was open from that branch.
In general, triggering on random WIP branches or say a branch created by clicking the "revert" button on a PR is not desired.
Example from gh-135:
=> CI: fix triggers for Sage CI jobs

.github/workflows/checks.yml, .github/workflows/ci-sage.yml, .github/workflows/tests-cygwin.yml, .github/workflows/tests.yml
This ensures that multiple jobs don't run for the same action. If a new commit is pushed, this cancels the jobs for the older commit. This is typically what is desired, and especially for longer-running jobs.
=> CI: add concurrency control to GitHub Actions workflows

mesonpy/__init__.py, noxfile.py
Mypy is extremely fragile, and random CI issues are going to crop up unless it is pinned.
=> TYP: fix a Mypy issue and pin Mypy 0.981

mesonpy/__init__.py, tests/packages/executable/example.c, tests/packages/executable/meson.build, tests/packages/executable/pyproject.toml, tests/test_wheel.py
=> BUG: fix issues with wheel tags, and add more tests to cover tags

mesonpy/__init__.py
You can only write a single file, or a directory that you can't specify the destination for with wheel.
I copy pasted the code and adjusted from wheel to do it.
cc @rgommers @FFY00
=> BUG: Fix meson-python failing on installing install_subdirs

mesonpy/__init__.py, mesonpy/_elf.py, tests/test_wheel.py
I also fixed `ELF.rpath`, which is needed for the tests, and added a test for setting the rpath in the first place in this PR.
Fixes #125
=> MAINT: skip setting rpath if it's not needed

mesonpy/__init__.py
=> BUG: honor MACOSX_DEPLOYMENT_TARGET

docs/index.rst, docs/usage/specific-behaviors.rst, mesonpy/__init__.py, tests/test_wheel.py
=> Use `mac_ver` instead of `sysconfig.get_platform` when determining the platform tag and document the MacOS platform tag handling

mesonpy/__init__.py, tests/test_wheel.py
=> BUG: ignore macOS minor version

mesonpy/__init__.py, tests/test_wheel.py
This is a follow-up to gh-161. From my review comment there:
However, the logic is wrong for macOS 10.x - there we _do_ want to preserve the major version, it should result in (e.g.) `10_13` and not `10_0`.
=> BUG: also handle macOS 10.X versions correctly

pyproject.toml, tests/test_wheel.py
We weren't sure if the fix we needed was getting backported, but it has been.
=> TST: update the test for `install_subdir` for fix in meson 0.63.3

.github/workflows/ci-sage.yml
Adding `opensuse-tumbleweed` as discussed in #172 @rgommers
Changing `opensuse-15.4` to `opensuse-15.4-gcc_11` to track a change in https://trac.sagemath.org/ticket/34266
=> CI: update opensuse platforms

tests/test_sdist.py
This was failing when building in Docker, see https://github.com/conda-forge/meson-python-feedstock/pull/7
=> TST: one more fix for the executable bit test

mesonpy/__init__.py, pyproject.toml
=> ENH: use tomllib on Python 3.11+

codecov.yml
This follows up on the discussion at the bottom of gh-165. The yaml content is the same as Meson uses.
For the docs, see https://docs.codecov.com/docs/commit-status#informational
[ci skip]
=> CI: set Codecov to "informational" to avoid spurious failures

noxfile.py, setup.cfg
Currently, you cannot select a specific testfile/test to run when running with nox. This allows specific tests to be selected and is backward compatible.
```bash
nox -s test-3.10 -- tests/test_pep517.py::test_get_requires_for_build_wheel
```
Didn't work before this PR.
=> TST: allow custom test selection

mesonpy/__init__.py, tests/packages/generated-files/example-script.py, tests/packages/generated-files/example.c, tests/packages/generated-files/executable_module.py, tests/packages/generated-files/generate_version.py, tests/packages/generated-files/meson.build, tests/packages/generated-files/pyproject.toml, tests/test_sdist.py
Generated files were not being added to the sdist.
This is useful for pandas, since we run a versioneer script to generate the sdist.
I think scipy avoids this, since they don't add generate a version file for their sdist?
I'll add a test, sometime in the future, but I'm a little busy now, so feel free to push to this branch in the meantime.
=> BUG: add generated files to sdist

LICENSE
Addresses the licensing part of gh-182.
[ci skip]
@lithomas1 please have a look, I hope this addresses your comments around copyright.
@FFY00 for the two changes I made to the old attribution:
- I combined the two lines for Quansight Labs and your name, because it seems like the common practice is to have the same date range combined on a single line
- and removed the email addresses because that seems unusual to have and subject to change. I'm sure we don't want/need the Quansight Labs email address there. For yours, I'd suggest it's better to get it from the commit log or your GitHub profile in case anyone wants to get in touch. But let me know if you prefer to keep it.
- Also to clarify for the record, I believe your name is separately listed because you reused some code that you had …
=> DOC: update copyright statements in LICENSE file

tests/packages/link-against-local-lib/meson.build, tests/packages/purelib-and-platlib/meson.build, tests/packages/scipy-like/meson.build, tests/test_wheel.py
In some of the test packages, the Python library is looked up incorrectly using dependency('python3') while the correct way is to use import('python').find_installation().dependency().
The correct lookup method could be used, but since Meson 0.63.0 python extension modules implicitly depend on the Python library and meson-python requires Meson 0.63.3. Just drop the explicit dependency.
=> TST: Fix test packages

.github/workflows/ci-sage.yml
So that the test suite can access PyPI during its tests.
=> CI: allow network access in the sage CI

mesonpy/__init__.py, mesonpy/_compat.py, tests/packages/dist-script/meson.build, tests/packages/dist-script/pyproject.toml, tests/packages/user-args/meson.build, tests/packages/user-args/pure.py, tests/packages/user-args/pyproject.toml, tests/test_project.py
=> ENH: allow users to pass options directly to Meson

.github/workflows/ci-sage.yml, pyproject.toml, tests/conftest.py, tests/test_pep518.py
=> TST: adding isolated build test

.github/workflows/checks.yml, .github/workflows/ci-sage.yml, .github/workflows/tests.yml
This should make it easier to work with CI required jobs. There are now just three required jobs: `checks-pass`, `sage-pass` and `tests-pass`.
=> CI: add pass jobs for both workflows

mesonpy/__init__.py, tests/packages/user-args/pyproject.toml
=> MAINT: rename the pyproject.toml tool config table to meson-python

mesonpy/_util.py
Remove an unnecessary `os.path.join()` call that broke when the output directory was a relative path.
This mistake was hidden in most cases because joining two absolute paths
together with os.path.join() results in the first path being dropped.
Fixes meson-python used with Tox.
=> BUG: Fix breakage when used with Tox

.flake8, mesonpy/__init__.py, pyproject.toml, tests/test_pep517.py
This uses the same solution as patchelf - if the system has it (and it's a new enough version, ~~1.7+ according to the release notes~~, 1.8.2 according to the meson error if missing), then use that. This fixes the build on systems that have a new enough ninja present but are not supportable by binary wheels.
See https://github.com/scikit-build/ninja-python-distributions/issues/127 for discussion.
=> ENH: use system ninja if adequate

mesonpy/__init__.py, tests/test_project.py
=> ENH: use dash in config options instead of an underscore

meson.build, mesonpy/__init__.py, mesonpy/_wheelfile.py, tests/conftest.py, tests/test_pep517.py, tests/test_wheelfile.py
The wheel package does not offer a public API.  Implement a minimal wheel file format writer to replace the use of the wheel package. This also reduces the number of external dependencies and will help a future integration of meson-python into Meson.  The produced wheel files are validated in the test suite inspecting them with the wheel package reader.
Fixes https://github.com/mesonbuild/meson-python/issues/192.
=> ENH: drop dependency on wheel

.github/workflows/sage.yml
The meson build infrastructure has been merged in Sage 9.8.beta4, so we can now test with the `develop` branch of Sage (which updates on every beta release.)
Also add another system package so that Sage does not have to build it from source.
=> CI: Use sage develop branch

mesonpy/__init__.py, tests/test_pep517.py
This adds the allowed keys to the error message (I was trying with `_` instead of `-` in a name, this would have cut my debugging time to seconds rather than a few minutes).
=> ENH: include allowed keys in error message

.github/workflows/tests.yml, ci/manylinux.docker, pyproject.toml
Now that meson-python can use the system provided ninja there is no need to depend on the PyPI package.
=> TST: remove ninja from test dependencies

mesonpy/__init__.py, mesonpy/_tags.py, mesonpy/_util.py, tests/conftest.py, tests/test_examples.py, tests/test_pep517.py, tests/test_pep518.py, tests/test_project.py, tests/test_tags.py
Use sysconfig.get_platform() instead of platform.mac_ver() to base the platform tag computation.  The ability to overwrite the value returned by former via the _PYTHON_HOST_PLATFORM environment variable is used in macOS extension modules cross-compilation.
See #222 for background.
=> ENH: support setuptools-style cross compilation on macOS

mesonpy/__init__.py, mesonpy/_compat.py, pyproject.toml, tests/test_examples.py, tests/test_pep517.py, tests/test_project.py
=> ENH: raise SystemExit when calling meson fails

.gitignore, docs/index.rst, meson.build, mesonpy/__init__.py, mesonpy/_compat.py, mesonpy/_editable.py, mesonpy/_introspection.py, mesonpy/_tags.py, noxfile.py, pyproject.toml, tests/conftest.py, tests/packages/imports-itself-during-build/meson.build, tests/packages/imports-itself-during-build/plat.c, tests/packages/imports-itself-during-build/pure.py, tests/packages/imports-itself-during-build/pyproject.toml, tests/packages/module-types/meson.build, tests/packages/module-types/native.c, tests/packages/module-types/pyproject.toml, tests/test_project.py, tests/test_wheel.py
~~This is just an initial approach, that is known to not work on all
use-cases. It simply uses .pth files to inject search locations for the
default import finder, for this reason generated files that should be
installed inside modules will not be available.~~
=> ENH: add support for editable wheels

mesonpy/__init__.py
In commit 13c6748a122bf7b5e887451165f66d33618dbe3b support was added for setting up cross file support based on the presence of $ARCHFLAGS, which is something that setuptools supported specifically for macOS.
It writes a Meson cross file out which is mostly correct, but it defines the C++ compiler in terms of the C preprocessor, which doesn't work. Fix this to use the correct program.
=> BUG: fix macOS support for cross-compiling C++

mesonpy/_util.py
PEP 517 does not specify whether sdist_directory or wheel_directory exist, and it may or may not do so.
Some projects that create it in advance, before calling our build_sdist and build_wheel hooks:
- pip
- pyproject-build
- gpep517
Some projects that do not create it:
- pdm
This may be a general problem in the ecosystem. Since nothing is specified, no one can assume anything -- the safest thing to do is have both the build backend and the build frontend create it, in order to ensure maximum compatibility between backends and frontends.
To make matters even more fun, pdm will delete the entire directory before invoking the build hooks. So even if you previously ran pyproject-build, pdm will delete the directory, then let meson-python fail because it doesn't exist.
Fixes …
=> BUG: fix creation of artifacts when the outdir does not exist

noxfile.py, pyproject.toml
This uses sphinx-autobuild to spawn the http server, as it as live-reload support.
I found this useful when doing final touch-ups on documentation pages.
=> DOC: add live-reload to the nox docs session when serving

mesonpy/__init__.py, mesonpy/_compat.py, mesonpy/_elf.py, mesonpy/_introspection.py, mesonpy/_tags.py, mesonpy/_util.py, mesonpy/_wheelfile.py, pyproject.toml
~~On top of #251, as it conflicts, and I don't want to have to rebase the PR after that gets merged.~~
As suggested in #248
Pros
- Drop the `typing-extensions` runtime dependency
Cons
- Unknown future, as we rely on `from __future__ import annotations`
- More complexity
- More unnecessary boilerplate
- This can be avoided by limiting `TYPE_CHECKING` to only when necessary
=> ENH: drop typing-extensions dependency

pyproject.toml
I updated the minimal version of `pyproject-metadata` because the versions < `0.7.0` have a bug on windows regarding the `utf-8` char decoding. 
I don't know if is it needed, because a a new installation already installs the `0.7.0` :man_shrugging:
=> ENH: change minimal version of pyproject-metadata

.pre-commit-config.yaml
Something seems to have broken in isort with the newest poetry release from I can tell. Anyway, update it to 5.12.0.
=> MAINT: update isort to 5.12.0 in pre-commit

mesonpy/__init__.py, tests/test_project.py
=> ENH: add install-tags filtering for wheel generation

README.md, docs/reference/limitations.rst, meson.build, mesonpy/__init__.py, mesonpy/_dylib.py, tests/test_wheel.py
This PR fixes linking against libraries created during the Meson build on macOS. It uses `otool` and `install_name_tool` to update the LC_RPATH load command in the dylib. (This is identical to how the library is patched on Linux.)
=> Fix linking against libraries from Meson project on macOS

README.md
there is a typo in the to the contributing docs in README.md
=> DOC: fix link to contributing docs

mesonpy/__init__.py, mesonpy/_compat.py, pyproject.toml
Having shorter lines for import statements enforced by isort started to give on my nerves...
=> CI: use same line length limit for ruff and isort 

tests/packages/subdirs/meson.build
The package is never used to build a wheel thus this fixes only a theoretical problem. But better have correct code in out codebase.
Fixes #295.
=> TST: fix test package meson.build

docs/reference/environment-variables.rst, mesonpy/_tags.py, tests/test_tags.py
This is the environment variable name used by Apple (see compat(5)). It is also supported by cibuildwheel, CMAKE, etc.
It was renamed in 9e84bd993c359721c3011cddd7f2403e5b019f74
Closes https://github.com/pypa/cibuildwheel/issues/1419
=> Rename MACOS_DEPLOYMENT_TARGET back to MACOSX_DEPLOYMENT_TARGET

mesonpy/__init__.py
Checking that the extensions modules filenames end with a suffix accepted by the current Python interpreter assumes that the wheel being assembled is for the same Python platform. This is not true when cross-compiling. The check protects against a very unlikely occurrence and makes life harder for tools that allow cross-compiling Python wheels. Remove it.
See #321.
=> ENH: do not check extension module file name against expected suffix

pyproject.toml
Use the normalized package name while at it.
=> TST: depend on Cython 3.0b1 to fix tests build issue on Python 3.12

mesonpy/__init__.py, tests/packages/unsupported-dynamic/meson.build, tests/test_metadata.py, tests/test_pep517.py, tests/test_project.py
Switch from an incomplete (an bugged) ad hoc validation to a scheme based validation strategy. The scheme is defined in the function _validate_pyproject_config() as nested dictionaries where the keys are configuration field names and valued are validation functions. Unknown fields result in an error.
Fixes #293.
=> BUG: improve validation of pyproject.toml meson-python configuration

mesonpy/__init__.py, mesonpy/_introspection.py, tests/test_tags.py
I think we can safely drop this now. The CI should agree.
=> ENH: remove fallback needed only with now unsupported Meson versions

mesonpy/__init__.py
When `ARCHFLAGS` is set to the empty string, meson-python breaks; see https://github.com/sagemath/sage/pull/35082#issuecomment-1464890197
=> Handle ARCHFLAGS set to the empty string

docs/how-to-guides/meson-args.rst
This is a draft for the (how-to) meson-args documentation. It includes an example for using meson install_tags using meson-python's install options (PR https://github.com/mesonbuild/meson-python/pull/288 and issue https://github.com/mesonbuild/meson-python/issues/68)
I could not yet answer all todos
(Mention the order in which Meson arguments are added, and how it affect Meson)
and
(Explain how you can add extra Meson arguments via the build config settings)
Feel free to comment on what you like/dislike or directly copy/modify it to you liking
=> DOC: add documentation for Meson arguments

mesonpy/__init__.py
Turn the warning emitted so far into an hard error: warnings are easy to miss when building packages containing many files and the reason for missing files in the installed wheel can be hard to track down.
Remove the message suggesting that a missing installation path placeholder in a Meson installation path is a Meson bug: this can be caused by the user using absolute paths as installation directories, for example using `py.get_path()` instead of `py.get_install_dir()`.
=> ENH: error on failure to map installed files into wheel directories

docs/explanations/default-options.rst, docs/index.rst, docs/reference/pyproject-settings.rst
This follows up on the `n_debug` default added in gh-325, documents all other default options and they are used, as well as improves the page on using `pyproject.toml` settings.
=> DOC: add details on default build options used by meson-python

mesonpy/__init__.py
This fixes B028.
> No explicit stacklevel keyword argument found. The warn method from the
> warnings module uses a stacklevel of 1 by default. This will only show a stack
> trace for the line on which the warn method is called. It is therefore
> recommended to use a stacklevel of 2 or greater to provide more information to
> the user.
I personally do not find this error very useful, but let's just pass the stacklevel argument and consider ignoring the error globally if we get more cases like this where this is the intended behavior.
=> MAINT: add stacklevel argument to warnings.warn

mesonpy/__init__.py
This use case is supported and extensively used in the meson-python test suite, there is no reason to emit a warning when a supported feature is used. This is accordance with PEP 621, which states that the lack of a "project" table in pyproject.toml implicitly means that the build back-end will dynamically provide all fields.
Fixes #306.
=> ENH: remove warning when package metadata generate from meson.build

docs/conf.py
Make the copyright statement shown in the documentation rendered pages consistent with the one declared in most documentation source files.
=> DOC: amend copyright statement

mesonpy/__init__.py, tests/test_pep517.py
Before
```
meson-python: error: A single line error message
```
```
meson-python: error: A multiline error message. Eg. X went wrong in the fields:
- aaa
- bbb
And Y went wrong in:
- ccc
- ddd
```
After
```
meson-python: error: A single line error message
```
```
meson-python: error:
>
> A multiline error message. Eg. X went wrong in the fields:
> - aaa
> - bbb
> 
> And Y went wrong in:
> - ccc
> - ddd
> 
```
With the latest commit, I kept single-line error the same, following the review, keeping the change for multi-line errors only.
Note, the error messages get nicely colorized too. The `>` line prefix is red, and the following is reset text.
=> ENH: format errors nicely on multiline error strings

docs/explanations/default-options.rst, mesonpy/__init__.py, tests/test_project.py
This ensure that the python interpreter path specified in the meson-python native file overrides any other provided in user supplied native files.
Fixes #330.
=> ENH: specify meson-python native file as last option to meson setup

docs/how-to-guides/meson-args.rst, mesonpy/__init__.py, tests/packages/detect-compiler/detect_compiler.c, tests/packages/detect-compiler/meson.build, tests/packages/detect-compiler/pyproject.toml, tests/test_project.py
Necessary if e.g. the user passes requests vsenv from meson setup.
(I guess I could restrict this to only when vsenv is requested in setup, but this needs thought as to how it would work with existing builddirs. I don't remember OTOH if we reconfigure the build dir if it exists already).
With this, pandas should be getting close to greenish again.
I still need to add a test for this, but this should be the right idea.
=> BUG: Use meson compile wrapper on Windows

.github/workflows/tests.yml
~~DO NOT MERGE~~
Meson 1.1.0 has been released, make sure to test with 1.0.1 too.
=> CI: add Meson 1.0 to the list of old releases being tested

mesonpy/__init__.py
=> BUG: fix system name specified when cross compiling via $ARCHFLAGS

mesonpy/__init__.py
Fixes #421.
- Do not strip tags from install plan.
- Strip tags in --tags argument
meson install have this behavior.
=> BUG: handle install plan with null tag

.github/workflows/tests.yml
Homebrew dropped support for Python 3.7.
=> CI: replace Python 3.7 with Python 3.8 on Homebrew

docs/contributing/release-process.rst
PyPI now discards uploaded GPG signatures and then emails you that it has done so.
This also cleans up the page a bit so the instructions are easier to follow.
=> DOC: update release process page, remove GPG-signing for PyPI

tests/test_options.py
Verify that the meson-python default meson arguments and user setup arguments result in the -DNDEBUG compilation flat to be set as expected.
=> TST: add test for handling of the -DNDEBUG compilation flag

.github/workflows/tests.yml, mesonpy/__init__.py, tests/packages/subproject/meson.build, tests/packages/subproject/pyproject.toml, tests/packages/subproject/subproject.py, tests/packages/subproject/subprojects/dep/dep.py, tests/packages/subproject/subprojects/dep/meson.build, tests/test_wheel.py
Requires introspection metadata added in upcoming Meson release 1.2.0.
Fixes #423.
=> ENH: implement --skip-subprojects install option

.github/workflows/tests.yml, mesonpy/__init__.py, tests/packages/missing-dynamic-version/meson.build, tests/packages/missing-dynamic-version/pyproject.toml, tests/packages/missing-meson-version/meson.build, tests/packages/missing-meson-version/pyproject.toml, tests/packages/missing-version/meson.build, tests/packages/missing-version/pyproject.toml, tests/packages/scipy-like/pyproject.toml, tests/test_project.py
This locally fixes a bug in pyproject-metadata.
Fixes https://github.com/mesonbuild/meson-python/issues/454.
=> BUG: fix handling of missing 'version' metadata field version

mesonpy/__init__.py, tests/test_editable.py, tests/test_options.py, tests/test_project.py, tests/test_wheel.py
This brings back the simplifications I proposed in #340 in a way compatible with having the wheel generated from files installed by `meson install` in a temporary destination directory. This covers a very minimal part of the work done in #348 too. It should be trivial to rebase #348 on top of this.
Fixes #355 and #330 as there are no arguments the user can supply that would interfere with meson-python internals. It also fixes #317 in the same way as #348 does.
=> ENH: remove the need for a working directory & other cleanups

docs/how-to-guides/debug-builds.rst, docs/index.rst
Closes gh-461
Closes gh-207
Also xref gh-459 and gh-441 which are already closed but contain discussion relevant to debug builds.
=> DOC: add a howto page on debug builds

CHANGELOG.rst
I've started to put together the changelog entry for the next release.
=> DOC: prepare changelog for 0.14.0 release

mesonpy/__init__.py
Allows $ARCHFLAGS enabled cross compilation of objc and objcpp.
Fixes #468.
=> ENH: add objc and objcpp to the $ARCHFLAGS generated cross file

mesonpy/__init__.py, tests/test_pep517.py
patchelf is required on Linux when executables, libraries, or extension modules in the package link to a shared library itself also distributed with the package.
To determine whether patchelf is required, the project to be built into a wheel needs to be configured. Because ephemeral build directories are used, the project needs to be configured a second time when the wheel is actually built. For all but the simplest projects the time spent in ``meson setup`` is significant.
This patch removes the check and thus the requirement for configuring the project twice, and assumes that patchelf is always required on Linux: dependency on the patchelf package is added when a suitable patchelf executable is not found in the environment.
Configuring the project requires ninja to be available. When …
=> ENH: always require patchelf on Linux

mesonpy/__init__.py, tests/packages/purelib-and-platlib/meson.build, tests/test_project.py, tests/test_tags.py, tests/test_wheel.py
This is an attempt at making the interface between the wheel builder class and the class representing the meson project a bit easier to understand.  Ideally we should be able to just pass the manifest and the metadata to the wheel builder class.
=> MAINT: restructure the interface between the project class and the wheel builder

docs/reference/environment-variables.rst, docs/reference/pyproject-settings.rst, mesonpy/__init__.py, pyproject.toml, tests/packages/vendored-meson/meson.build, tests/packages/vendored-meson/meson_options.txt, tests/packages/vendored-meson/pyproject.toml, tests/packages/vendored-meson/third-party/meson.py, tests/test_wheel.py
Allow using a MESON environment variable, analogous to the NINJA one, or a string to an executable or Python script in the `[tool.meson-python]` section of `pyproject.toml`.
Addresses gh-458.
Package authors are likely going to need/prefer the `tool.meson-python` setting, as discussed in gh-458. For local development or user overrides the environment variable will be useful; it is implemented analogous to the NINJA one.
This will allow me to unvendor `meson-python` from `numpy`, as tested in [this branch](https://github.com/rgommers/numpy/tree/unvendor-mesonpython) with these changes:
<details>
```diff
[build-system]
build-backend = "mesonpy"
-backend-path = ['./vendored-meson/meson-python']
requires = [
"Cython>=3.0",
-    # All dependencies of the vendored meson-python (except for …
```
=> ENH: make the Meson executable user-configurable 

.mailmap
The added mailmap files fixes two alternative spellings of Matthias Köppe's name and adds a name for metab0t beside the Github username. This is useful for generating the contributors list we add to the changelog.
=> MAIN: add a .mailmap file

mesonpy/__init__.py, mesonpy/_compat.py, mesonpy/_util.py, pyproject.toml
Counting starting at zero is nice and nerdy, but logging that meson-python is installing zero of zero files when is actually installing something is confusing.
=> ENH: count installed files starting at one

docs/how-to-guides/meson-args.rst
There is already one at the end of the command (which matches the `pypa/build` version.)
=> DOC: Remove extra '.' in meson args examples

mesonpy/_wheelfile.py, tests/test_wheelfile.py
As pointed out in
https://docs.python.org/3/library/zipfile.html#zipfile.ZipFile.writestr
when creating a ZipInfo it defaults to ZIP_STORED and when passing it
to writestr it will use the compression info from the ZipInfo instance
instead of the ZipFile. This leads to the wheel file being
uncompressed.
To fix this explicitely specify the compression type and level for
writestr() so it gets applied to the ZipInfo instance before writing.
While the compression level currently isn't used I also added it to
avoid future surprises.
Fixes #519
=> BUG: Fix wheels not being compressed

CHANGELOG.rst, docs/reference/config-settings.rst, meson.build, mesonpy/__init__.py
We accumulated a few important bug fixes and new features, so it seems time for a release.
@dnicolodi I set the date to today - in case it gets merged later, that date should be updated right before the merge.
=> DOC/REL: prepare 0.15.0 changelog and release

.readthedocs.yaml
The problem was that they migrated to a new yaml version, plus that notifications on build failures in the RTD UI was not enabled for anyone.
Closes gh-522
=> DOC: fix Read the Docs builds

mesonpy/__init__.py
Correctly detect a wheel shipping shared libraries as being platform dependent also when it does not ship compiled executables or Python extension modules.
=> BUG: fix detection of platform dependent components in wheel

pyproject.toml
This is the same email address that is used in the for the git commits. This should fix how the Maintainers metadata field is rendered on the PyPI package page.
=> MAINT: use placeholder email address for Thomas Li in pyproject.toml

.cirrus.yml, mesonpy/_tags.py, tests/test_tags.py
=> BUG: use 11.0 as minimum macOS platform ABI tag on arm64

.github/workflows/docs.yml, docs/index.rst
This is very simple and does not allow for multiple versions of the documentation to be published. I think it would not be too hard to add, but I don't think it would add much value for the meson-python documentation.
=> DOC: deploy documentation using Github Pages

mesonpy/__init__.py, mesonpy/_util.py, pyproject.toml, tests/test_output.py
Simply enable ANSI escape sequences processing on the Windows console. This works only on Windows 10 and later, and colorama does the same thing when it can.
=> ENH: drop dependency on colorama on Windows

.github/workflows/tests.yml, ci/alpine-3.docker, ci/debian-11.docker, ci/debian-12.docker, ci/fedora-37.docker, ci/miniconda.docker
The tests are run with the latest Meson version, and Meson 1.3 has been released a while ago. Add Meson 1.2 to the old releases with test with. Pin the version to 1.2.3 or later, to be able to run on Python 3.12.
=> CI: extend matrix to include Meson 1.2

mesonpy/__init__.py, mesonpy/_editable.py, tests/packages/custom-target-dir/codegen.py, tests/packages/custom-target-dir/meson.build, tests/packages/custom-target-dir/pyproject.toml, tests/test_editable.py, tests/test_wheel.py
Meson support custom_target() whose output is not a file but a directory. Support these in meson-python mapping of installation paths to wheel locations. Replaces #571.
=> ENH: support custom_target() installing a directory

docs/reference/environment-variables.rst, docs/reference/pyproject-settings.rst, pyproject.toml
- cross link to the tables of compiler/linker flags in the Meson docs
- mention `PKG_CONFIG_PATH`
- add a warning about Conda's habit of injecting env vars also on the environment variables reference page
Closes gh-460
=> Extend documentation on environment variables

ci/alpine-3.docker
Alpine Linux replaces ninja with samurai in the default installation. Meson and meson-python work with either, however, the version of samurai available in Alpine Linux segfaults when invoked with the -n options. Having to deal with this in the test suite is a pain. Switch to proper ninja.
=> CI: install real ninja in Alpine Linux image

.github/workflows/tests.yml
Meson 1.4 has been released, thus all tests normally run with it.
=> CI: add Meson 1.3 to the old meson releases we test with

pyproject.toml
We were relying on `pyproject-metadata` adding a `packaging` dependency implicitly. We use it directly though, so should add it in our own metadata. We have no particular version requirements beyond what is needed by `pyproject-metadata`, so we add the same >=19.0 constraint.
This follows up on https://github.com/mesonbuild/meson-python/pull/612#issuecomment-2060528062
=> BLD: add missing dependency on `packaging`

CHANGELOG.rst, meson.build, mesonpy/__init__.py
@rgommers Unless you have anything against it I'm going to get this out of the door in the next few days. The pending PRs will be material for 0.17.0
=> Prepare release 0.16.0

mesonpy/__init__.py
Prompted by https://github.com/mesonbuild/meson/issues/13154
=> BUG: be more careful with encodings

docs/how-to-guides/config-settings.rst, docs/reference/config-settings.rst
Closes gh-540
Also touches on gh-246, which is a common enough hiccup that it's useful to explicitly show dealing with `meson-log.txt` in CI.
=> DOC: add docs on using the `build-dir` config setting

mesonpy/__init__.py
This is a follow-up to gh-495.
There are several ways that meson may go missing:
- a non-isolated build and meson isn't installed
- meson executable is specified in pyproject.toml and git submodule is containing it is not initialized (reported as resulting in a confusing error in https://github.com/numpy/numpy/issues/26397)
- the  `MESON` environmnent variable is used by the user and is misspelled
The git submodule case was ending with:
```
meson-python: error: Could not find meson version 0.63.3 or newer, found .
```
and after this ends with:
```
meson-python: error: Could not find specified meson: vendored-meson/meson/meson.py
```
If the executable is missing, the build ended with a very long traceback. Changing `FileNotFoundError` to `ConfigError` elides the traceback and clearly …
=> MAINT: improve error message when meson isn't found

tests/packages/complex/extension.c
Add support for the experimental free-threading Python version in the complex.extension module.
closes #654
=> add free threading support to complex.extension

.pre-commit-config.yaml, pyproject.toml, tests/test_editable.py
Perform a periodic update of the tools in [`pre-commit`](https://pre-commit.com).
% `pre-commit install`
```
pre-commit installed at .git/hooks/pre-commit
```
% `pre-commit autoupdate`
```
[https://github.com/pre-commit/pre-commit-hooks] updating v4.5.0 -> v4.6.0
[https://github.com/astral-sh/ruff-pre-commit] updating v0.1.5 -> v0.5.5
[https://github.com/fsfe/reuse-tool] updating v2.1.0 -> v4.0.3
```
% `pre-commit run --all-files`
```
[ ... ]
ruff.....................................................................Failed
- hook id: ruff
- files were modified by this hook
warning: The top-level linter settings are deprecated in favour of their counterparts in the `lint` section. Please update the following options in `pyproject.toml`:
- 'extend-ignore' -> 'lint.extend-ignore'
- 'select' -> …
```
=> MAINT: pre-commit autoupdate 2024-07-31

docs/conf.py
* From: @lamby
Make the documentation reproducible when rebuilt
The Reproducible Builds project aims to arrange for rebuilding the same
source code in a sufficiently similar environment to produce the same
installable packages every time, as a way to discourage supply-chain
attacks by making it possible to verify that a particular installable
package was built from the claimed source code.
Previously, if meson-python was built twice, at least a year apart,
then its documentation would contain different copyright dates. The
SOURCE_DATE_EPOCH environment variable is used here to avoid that
difference: the intention is that environments that want to produce
reproducible packages will set SOURCE_DATE_EPOCH to some suitable fixed
date (perhaps the date of the most recent git commit) which is …
=> DOC: make the documentation reproducible when rebuilt

.github/workflows/tests.yml
This is required now, it was a breaking change in `codecov-action@v4`. Follows up on https://github.com/mesonbuild/meson-python/pull/479#issuecomment-2265134409.
The token didn't exist yet; I just added it as a repository secret.
=> CI: use a token for the Codecov action to upload

.cirrus.yml, ci/alpine-3.docker, ci/opensuse-15.docker
The Free BSD 13.2 VM image used so far has been retired.
=> CI: update Cirrus CI job to use FreeBSD 14.0

mesonpy/__init__.py, tests/test_tags.py, tests/test_wheel.py
Pip does not support installing PyPy wheels with the abi3 tag. If you build a wheel for PyPy and set the ABI tag to `abi3`, pip will not be able to install it.
```
$ docker run --rm -it quay.io/pypa/manylinux2014_x86_64
[root@cd7b2d465170 /]# /opt/python/pp39-pypy39_pp73/bin/python
Python 3.9.19 (a2113ea87262, Apr 21 2024, 05:40:24)
[PyPy 7.3.16 with GCC 10.2.1 20210130 (Red Hat 10.2.1-11)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>>> from pip._internal.utils.compatibility_tags import get_supported
>>>> for tag in get_supported():
....     print(tag)
....
pp39-pypy39_pp73-manylinux_2_17_x86_64
pp39-pypy39_pp73-manylinux2014_x86_64
```
Full output:
<details>
```
>>>> from pip._internal.utils.compatibility_tags import get_supported
>>>> for tag in …
```
=> Disable abi3 wheel tag for PyPy

mesonpy/_editable.py, tests/test_editable.py
When using meson editable install, this can be very suprising that there is no obvious error when recompilation fails.
One use case I bumped into:
1. I modify a scikit-learn cython file and introduce a compilation error
2. I run my scikit-learn test `pytest sklearn/.../test_bla.py` that imports scikit-learn and should recompile when needed
What happens:
The test run so I thought everything was fine, but actually the recompilation failed and I did not notice because `pytest` captures the output. If I had done `pytest -s` and looked carefully at the output I may have noticed
What I would expect:
There is an explicit error that tells me that recompilation failed.
With the current change, the tests run fine locally but there may be a side-effect I have not thought of?
This is how the output …
=> Editable install: raise ImportError when rebuilding fails

mesonpy/_tags.py
Add change of `tags.py` from https://github.com/pypa/packaging/pull/711. It is necessary to get correct tags on GraalPy, because GraalPy has lower `sys.maxsize` on 64-bit due to JVM limitations.
=> Sync tags change from packaging to support GraalPy

.github/workflows/tests.yml
Homebrew discontinued CPython 3.8. Switch testing Python 3.9 and 3.13 on this platform. Add CPython 3.13 to the regular test matrix.
=> ci: Update Python versions

docs/tutorials/introduction.rst
Build isolation is a regular cause of confusion for many users, so a brief explanation can't hurt.
Also add a very brief note that the build venv must be activated - the `venv` docs are confusing here, as gh-630 shows. Closes gh-630
=> DOC: add a brief explanation of build isolation to the tutorial

meson.build, mesonpy/__init__.py
The 0.17.0 release is up.
In the `0.17.0` tag we did unfortunately forget to bump the version string in the docs, so the deployed docs say `0.17.0.dev0`. Not a major issue, but a slight annoyance - needs a manual docs deployment to fix.
=> MAINT: set version to 0.18.0.dev0

tests/test_sdist.py
=> TST: fix test to work correctly outside git work directory

CHANGELOG.rst
Forward-port the update to the release notes to `main`
(cherry picked from commit a2063744a24dacc10db83583f9f3c33ef79ff4ca)
=> DOC: update changelog for 0.17.1

.github/workflows/tests.yml, docs/reference/meson-compatibility.rst, pyproject.toml, tests/packages/subdirs/meson.build
Depending on 0.64.0 or later allows to use the pure argument when invoking the import('python').find_installation() Meson function, which makes for some nicer test and example code. Meson 0.64.0 was released on November 6th, 2022, just over a month after the current minimum supported version.
=> MAINT: bump minimum required Meson version to 0.64.0

.cirrus.yml, RELEASE.rst, ci/archlinux.docker, ci/debian-12.docker, ci/fedora-41.docker, mesonpy/__init__.py, tests/test_consistency.py
The module constant has been used to check meson-python version in other projects, see discussion on #691.  Add a test to ensure that the version recorded in `pyproject.toml` and `mesonpy/__init__.py` are kept in sync.
=> MAINT: put back mesonpy.__version__

docs/how-to-guides/shared-libraries.rst, docs/index.rst, tests/packages/link-library-in-subproject/foo/__init__.py, tests/packages/link-library-in-subproject/foo/_examplemod.c, tests/packages/link-library-in-subproject/foo/meson.build, tests/packages/link-library-in-subproject/meson.build, tests/packages/link-library-in-subproject/pyproject.toml, tests/packages/link-library-in-subproject/subprojects/bar/bar_dll.h, tests/packages/link-library-in-subproject/subprojects/bar/examplelib.c, tests/packages/link-library-in-subproject/subprojects/bar/examplelib.h, tests/packages/link-library-in-subproject/subprojects/bar/meson.build, tests/packages/sharedlib-in-package/meson.build, tests/packages/sharedlib-in-package/mypkg/__init__.py, tests/packages/sharedlib-in-package/mypkg/_examplemod.c, tests/packages/sharedlib-in-package/mypkg/examplelib.c, tests/packages/sharedlib-in-package/mypkg/examplelib.h, tests/packages/sharedlib-in-package/mypkg/meson.build, tests/packages/sharedlib-in-package/mypkg/sub/examplelib2.c, tests/packages/sharedlib-in-package/mypkg/sub/examplelib2.h, tests/packages/sharedlib-in-package/mypkg/sub/meson.build, tests/packages/sharedlib-in-package/mypkg/sub/mypkg_dll.h, tests/packages/sharedlib-in-package/pyproject.toml, tests/test_wheel.py
~_Opening this PR now to get feedback on topics and structure, not ready for detailed review yet._~
We get a lot of questions about shared libraries, and this is a tricky thing to get right. So try to document how to use internal libraries as well as link to external shared libraries as well as possible. Subproject-related questions also come up more and more, and there are some extra gotchas here, so treat those as a third "source" of shared (or static) libraries.
- Closes gh-539
- xref gh-525 and gh-551 for internal shared libraries on Windows
- xref gh-410 and gh-556 for optionally bundled a shared library
- xref gh-629 for shared library in subproject use cases
=> DOC: add documentation about using shared libraries

.github/workflows/tests.yml
Pyston is unmaintained. The most recent Pyston packages are only available for for Ubuntu 20.04. GitHub Actions is dropping support for this distribution. With this it is becoming more demanding to test this interpreter. The latest Pyston release support Python 3.8, which is EOL for CPython. meson-python does not have any Pyston specific code. Maintaining test coverage for this interpreter does not seem worth the effort that it would require.
=> CI: drop Pyston from test matrix

pyproject.toml
pyproject-metadata 0.9.1 requires packaging 23.2 or later, but does not record this dependency, see https://github.com/pypa/pyproject-metadata/pull/239
This becomes a problem when meson-python is installed on a platform where packaging 19.0 (the current minimum required version) is installed. This does not trigger an update of packaging to the latest available version and results in run time errors, see https://github.com/scipy/scipy/pull/22840#issuecomment-2817494211
This could be fixed by a new release of pyproject-metadata, but we do not want meson-python to depend on very recent releases. meson-python supports pyproject-metadata 0.9.0 or later and still carries some work-arounds for issues in that release.
The least invasive and most effective solution is to bump the packaging …
=> MAINT: bump minimum packaging version to 23.2

pyproject.toml
meson-python uses itself as a build backend, thus we can switch to PEP639 license declaration now that meson-python supports it.
=> MAINT: switch to PEP639 license declaration for meson-python itself

mesonpy/__init__.py, tests/packages/symlinks/meson.build, tests/packages/symlinks/pyproject.toml
Modifies the existing `symlinks` test package so it exercises the bug. The situation without a `version` keyword in `meson.build` is more difficult because the dist tarball generated by Meson will be named `<project-name>-undefined.tar.gz`, which meson-python then changes to `<project-name-version.tar.gz`.
_Note: I didn't include the dist script part discussed in https://github.com/mesonbuild/meson-python/pull/728#issuecomment-2848691677, because I'm out of time right now. I think it should be done, but it's not blocking for 0.18.0 I think._
=> BUG: fix a problem with symlink support

docs/reference/environment-variables.rst, docs/reference/meson-compatibility.rst, mesonpy/__init__.py, mesonpy/_tags.py, pyproject.toml, tests/test_project.py, tests/test_tags.py
Adds the modifications required to support targeting iOS.
Assumes meson is running in a cross-platform virtual environment, where `sys.platform == "ios"`, and other platform identification tags are "mocked" versions of an iOS environment (matching what cibuildwheel's iOS support does).
Functionally, it's very similar to macOS build support - it writes a cross-build configuration file, based on the contents of sysconfigdata.
The bump in the version of Packaging is required so that iOS platform tag handling is available.
=> Add support for targeting iOS.

pyproject.toml
Add configuration for the ruff formatter to enforce single quotes for strings, otherwise it constantly reformats the strings to double-quotes.
=> MAINT: add config for ruff formatter

pyproject.toml
This change fixes something that may be invalid TOML, aligns better with the docs at https://docs.astral.sh/ruff/configuration, and avoids Pixi choking on parsing `pyproject.toml` with:
```
79 │ lint.extend-ignore = [
· ──┬─
·   ╰── first defined here
80 │   'B019',
81 │ ]
...
98 │
99 │ [tool.ruff.lint.flake8-quotes]
·            ──┬─
·              ╰── duplicate defined here
```
=> MAINT: fix ruff configuration in pyproject.toml

tests/test_tags.py
=> TST: harden against environment variables affecting meson-python

docs/how-to-guides/shared-libraries.rst
Updates install_path to install_dir. 
Updates code block to be more explicit with shared_library usage.
Fixes #769
=> DOC: shared-libraries: fix and clarify install location example

mesonpy/__init__.py
Extracted from #768. `strip` has been added to the CPython distributed compiler wrappers, use that.
=> ENH: define strip binary in synthesized cross files

.gitattributes, tests/test_sdist.py
Follows up on https://github.com/mesonbuild/meson-python/pull/728#issuecomment-2848691677 and gh-745.
=> MAINT: avoid warnings because of symlinks pointing outside repo
