tests/test_metadata.py

tests: metadata: fix tests for the new pep621 version

---

mesonpy.py

mesonpy: use absolute path for source and working directories

---

mesonpy.py

mesonpy: fix internal install location

---

mesonpy.py
tests/test_wheel.py

mesonpy: add missing tags to is_pure check

---

mesonpy.py
pyproject.toml
setup.cfg
tests/test_tags.py
tests/test_wheel.py

mesonpy: select the correct ABI tag

---

mesonpy.py
tests/test_wheel.py

mesonpy: select the correct Python tag

---

mesonpy.py

mesonpy: force Meson to use the current Python executable

---

meson.build
mesonpy/__init__.py
mesonpy/_compat.py
mesonpy/_tags.py
mesonpy/_util.py
tests/test_tags.py

mesonpy: refactor module into a package

---

README.md

readme: add usage

---

meson.build
mesonpy/__init__.py
mesonpy/_elf.py
mesonpy/_tags.py
tests/conftest.py
tests/packages/link-against-local-lib/examplelib.c
tests/packages/link-against-local-lib/examplelib.h
tests/packages/link-against-local-lib/examplemod.c
tests/packages/link-against-local-lib/meson.build
tests/packages/link-against-local-lib/pyproject.toml
tests/test_pep517.py
tests/test_wheel.py

mesonpy: replace auditwheel with an in-house vendoring mechanism

---

README.md

ah! third time's the charm :sweat_smile:

readme: fix typo (aginst > against)

---

docs/usage/start.rst

docs: improve the automatic metadata section

---

pyproject.toml

pyproject: add colorama dependency on Windows

---

README.md

readme: update status regarding platform support

---

docs/index.rst

docs: update platform support status

---

README.md

readme: rename project

---

mesonpy/__init__.py

Signed-off-by: Filipe Laíns <lains@riseup.net>Signed-off-by: Filipe Laíns <lains@riseup.net>

mesonpy: minor wheel builder documentation enhancement

---

mesonpy/__init__.py

mesonpy: set default arguments for release

---

mesonpy/__init__.py
tests/packages/full-metadata/pyproject.toml
tests/packages/unsupported-python-version/meson.build
tests/packages/unsupported-python-version/pyproject.toml
tests/test_metadata.py
tests/test_project.py

mesonpy: error out if we are running on an unsupported interpreter

---

mesonpy/__init__.py

mesonpy: allow pre-releases when checking the interpreter version

---

mesonpy/__init__.py

Fixes #74
@tylerjereddy or @rgommers could you verify that this does indeed fix your issues with SciPy on Debian?

mesonpy: fix slightly broken Debian heuristics

---

mesonpy/__init__.py

DOC: improve documentation of most things in the mesonpy module

---

tests/test_wheel.py

TST: fix test_contents_license_file on Windows

---

tests/test_sdist.py

*sighs*
It was a stupid issue :sweat_smile: 
Fixes #86

TST: fix test_contents_unstaged outside git clones 

---

mesonpy/__init__.py

BUG: fix ABI tag calculation when Meson returns a full path

---

pyproject.toml

BLD: get version dynamically from the Meson metadata

---

meson.build
mesonpy/__init__.py

REL: update version to 0.8.0.dev0

---

.github/workflows/tests-cygwin.yml
.github/workflows/tests.yml

TST: report coverage if tests fail in CI

---

.github/workflows/checks.yml
.github/workflows/tests-cygwin.yml
.github/workflows/tests.yml
tests/test_output.py

TST: force colors on CI

---

mesonpy/__init__.py

BUG: fix mapping tags

---

meson.build
mesonpy/__init__.py

REL: update version to 0.9.0.dev0

---

mesonpy/__init__.py

BUG: fix unbound from_heuristic variable

---

mesonpy/__init__.py

Project.platform_tag: Handle the case of 32bit Python on x86_64

---

.github/workflows/ci-sage.yml

Using the reusable workflows from SageMath
Fixes #76

CI: Run tests against Python from Debian, Fedora, Centos, Gentoo, Archlinux, OpenSUSE, conda-forge

---

mesonpy/__init__.py

Fixes #124 
@jeandet could you give this a try? Please keep in mind that sdist generation is currently broken in `main` (#120).

BUG: fix ABI tag on Debian

---

.github/workflows/tests.yml
mesonpy/__init__.py
mesonpy/_tags.py
tests/test_tags.py
tests/test_wheel.py

@mattip can you have a look?
EDIT: addresses gh-121

BUG: handle PyPy tags correctly

---

.github/workflows/tests.yml
noxfile.py

Co-Authored-by: layday <layday@protonmail.com>

CI: fix PyPy

---

.github/workflows/ci-sage.yml

As requested in #150 @rgommers

CI: Do not build scipy

---

.github/workflows/ci-sage.yml
pyproject.toml

.github/workflows/ci-sage.yml: Make sure git is available

---

.gitignore
docs/examples/spam/meson.build
docs/examples/spam/pyproject.toml
docs/examples/spam/src/__init__.py
docs/examples/spam/src/spammodule.c
tests/docs/examples/conftest.py
tests/docs/examples/test_spam.py
tests/test_wheel.py

I've been using meson-python for building C extensions to python a lot recently. Starting out, I would have benefited from a really simple example with some documentation. This PR adds a simple example adapted from https://docs.python.org/3/extending/extending.html.
- Added a `spam` example C extension. This is mostly taken from https://docs.python.org/3/extending/extending.html, but I added some more comments and modified the project structure a bit - hopefully users find the changes instructive.
- Added a test that checks that the example builds, installs, and can be imported. 
- If I remember correctly if a problem is encountered with setting up fixtures, the whole pytest session fails. So for that reason the test for the `spam` example builds and imports the example in a virtual …

DOC: add a simple C extension example

---

pyproject.toml
tests/test_wheel.py

Unconditionally require Meson subdir fix

---

mesonpy/__init__.py
tests/test_wheel.py

BUG: generate entry_points.txt file

---

.github/workflows/ci-sage.yml

CI: build smaller images

---

.github/workflows/sage.yml
.github/workflows/tests.yml

I think we are gonna run into #8926 because of the required checks, and AFAIK there's no sane way to handle it, we need to copy the test matrix over to a new workflow, but lets see how it goes.

CI: skip tests on documentation changes

---

pyproject.toml

BUG: be consistent about pyproject-metadata version requirement

---

.github/workflows/tests.yml
tests/test_wheel.py

I don't expect any surprise, but release candidates are made to be tested, thus do our good citizens duty.

CI: test with Meson 1.0.0rc1

---

CHANGELOG.rst

DOC: update CHANGELOG.rst for change to ``typing_extensions`` dependency

---

mesonpy/__init__.py
mesonpy/_compat.py
pyproject.toml

ENH: drop importlib_resources dependency

---

.pre-commit-config.yaml

MAINT: update pre-commit commit message to follow our new guidelines

---

.flake8
.pre-commit-config.yaml
mesonpy/__init__.py
mesonpy/_introspection.py
mesonpy/_tags.py
pyproject.toml
tests/test_sdist.py
tests/test_tags.py
tests/test_wheel.py

ENH: move to ruff

---

README.md

The latest docs are significantly better right now, we can reconsider moving back to the stable docs after release.

DOC: link to latest docs in readme

---

docs/how-to-guides/first-project.rst

Fix a typo and grammar issue, and also add a quick introduction about Meson and how it integrates with meson-python.

First project guide fixups

---

docs/examples/spam/meson.build
mesonpy/__init__.py
tests/packages/purelib-platlib-split/meson.build
tests/packages/purelib-platlib-split/plat.py
tests/packages/purelib-platlib-split/pure.py
tests/packages/purelib-platlib-split/pyproject.toml
tests/test_wheel.py

I've tried to make the error message concise but informative. I'm not sure I succeeded.

ENH: detect packages installed both in purelib and platlib

---

meson.build
mesonpy/__init__.py

Thought it's best to have a PR for this as well. Once this is in, I'll create and push a GPG-signed tag for the 0.13.0 commit.

REL: commit for 0.13.0 release, then set version to 0.14.0.dev0

---

tests/conftest.py
tests/test_editable.py
tests/test_project.py

TST: fix test when not executed from git checkout

---

docs/examples/spam/meson.build
meson.build
tests/packages/complex/meson.build
tests/packages/configure-data/meson.build
tests/packages/detect-compiler/meson.build
tests/packages/dist-script/meson.build
tests/packages/dynamic-version/meson.build
tests/packages/executable-bit/meson.build
tests/packages/executable/meson.build
tests/packages/full-metadata/meson.build
tests/packages/generated-files/meson.build
tests/packages/imports-itself-during-build/meson.build
tests/packages/library-pep621/meson.build
tests/packages/library/meson.build
tests/packages/license-file/meson.build
tests/packages/link-against-local-lib/meson.build
tests/packages/module-types/meson.build
tests/packages/pure/meson.build
tests/packages/purelib-and-platlib/meson.build
tests/packages/purelib-platlib-split/meson.build
tests/packages/scipy-like/meson.build
tests/packages/scipy-like/mypkg/meson.build
tests/packages/simple/meson.build
tests/packages/subdirs/meson.build
tests/packages/unsupported-python-version/meson.build
tests/packages/user-args/meson.build

meson.build cleanup

---

mesonpy/__init__.py
tests/test_project.py
tests/test_tags.py
tests/test_wheel.py

The latter is not well defined on some systems.

MAINT: use sys.platform instead of platform.system()

---

docs/index.rst
docs/tutorials/introduction.rst

DOC: clean up front page and intro tutorial, state files must be in VCS

---

README.rst

The main goal is to be able to have CI run in each push in https://github.com/mesonbuild/meson-python/pull/579. cc @rgommers

Minor README tweak

---

.pre-commit-config.yaml

https://pre-commit.ci/#configuration
> possible values: 'weekly', 'monthly', 'quarterly'.
As requested at https://github.com/mesonbuild/meson-python/pull/651#pullrequestreview-2215094986

MAINT: .pre-commit-config.yaml: autoupdate_schedule: quarterly
